### ISSUE TITLE
[Package request] Noise-repellent 0.1.3

### ISSUE THREAD

**Issue by lucianodato** [KXStudio/Repository#136] opened 2017-10-26 19:35 UTC
Hi falktx!
I would love to see my plugin in your repo. I'm not experienced at all in making this kind of packaging and I'm hoping if it's not too much trouble for you to include it in kxstudio. Lastest release is at https://github.com/lucianodato/noise-repellent/releases
Let me know what do you think.

Cheers!
Luciano

**Comment by wolftune** [comment] 2018-01-04 19:00
This should be closed as dupe of #116

**Comment by lucianodato** [comment] 2018-01-04 20:36
Sorry, didn't saw that one at first glance.

**Comment by wolftune** [comment] 2018-01-04 22:07
No worries, but as the person who opened this, you should have permission to close it.

**Closed** 2018-01-05 11:42 UTC
