### ISSUE TITLE
APT warning about repos being configured multiple times

### ISSUE THREAD

**Issue by AVLinux** [KXStudio/Repository#88] opened 2016-12-14 03:47 UTC
Hi,

Recently after upgrading to kxstudio-repos and kxstudio-repos-gcc5 9.4.1 I get the following APT errors when running 'apt-get update'

```
W: Target Contents-deb-legacy (Contents-amd64) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.gcc5.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.gcc5.list:1
W: Target Contents-deb-legacy (Contents-i386) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.gcc5.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.gcc5.list:1
W: Target Contents-deb-legacy (Contents-all) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.gcc5.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.gcc5.list:1
W: Target Contents-deb-legacy (Contents-amd64) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.list:1
W: Target Contents-deb-legacy (Contents-i386) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.list:1
W: Target Contents-deb-legacy (Contents-all) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.list:1
W: Target Contents-deb-legacy (Contents-amd64) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.gcc5.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.gcc5.list:1
W: Target Contents-deb-legacy (Contents-i386) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.gcc5.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.gcc5.list:1
W: Target Contents-deb-legacy (Contents-all) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.gcc5.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.gcc5.list:1
W: Target Contents-deb-legacy (Contents-amd64) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.list:1
W: Target Contents-deb-legacy (Contents-i386) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.list:1
W: Target Contents-deb-legacy (Contents-all) is configured multiple times in /etc/apt/sources.list.d/kxstudio-free.list:1 and /etc/apt/sources.list.d/kxstudio-non-free.list:1
root@avlinux64box:/home/tester# 
```
I tried to fix this by manually deleting ALL of the kxstudio lists in /etc/apt/sources.list.d then completely removing the 'kxstudio-repos' and 'kxstudio-repos-gcc5' packages from the system which should have completely purged all kxstudio repositories. I then manually installed the kxstudio repository debs from the KXStudio website and reloaded Synaptic and the errors above appeared again from a fresh install of the repo debs. Is something in the lists themselves formatted improperly?

**Comment by falkTX** [comment] 2016-12-14 08:06
Seems to be caused by a debian testing change that is yet to be explained.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839259

**Comment by falkTX** [comment] 2017-05-09 14:56
I was never able to reproduce this.
Is it still an issue?

**Comment by AVLinux** [comment] 2017-05-09 16:52
Yes it is on Debian Squeeze anyway...

If you DL AV Linux 2017.4.9 and boot it on a LiveUSB or in Virtualbox Reloading Synaptic or apt-get update should produce the error.

http://bandshed.net/test/iso/

**Comment by alepeccioli** [comment] 2017-05-17 10:37
I followed this tutorial: https://www.youtube.com/watch?v=0UDTF_ndQ1E and the bug has been fixed ...

**Comment by AVLinux** [comment] 2017-08-31 04:59
Hi, I got away from troubleshooting this and want to resolve it for the next AVL release unfortunately alepeccioli's link on Youtube is no longer available. @alepeccioli  do you remember what you did?

**Comment by alepeccioli** [comment] 2017-08-31 09:15
I do not remember anymore, but I'll do a search and see if I can get any information...

**Comment by falkTX** [comment] 2017-08-31 10:57
I got myself a debian testing chroot but this didn't got reported there.
@AVLinux  can you try to `apt-get purge kxstudio-repos*` and re-enable them again, to see if this makes any difference?

**Comment by AVLinux** [comment] 2017-09-05 01:30
@falkTX 

OK,

If you look a few posts up that was the first thing I tried, but I'll try again... so far I've purged the repos and the errors have disappeared... 

Reinstalled the Repo Debs from: http://kxstudio.linuxaudio.org/Repositories

The errors have returned as before unfortunately.

**Comment by falkTX** [comment] 2017-09-05 08:11
What is the quickiest way for me to reproduce this?
Can I install the latest AVLinux image and the error appears there right away?

**Comment by AVLinux** [comment] 2017-09-05 13:40
Hi,

Even a Live boot on a USB key and reloading Synaptic or running apt-get update should reproduce it, you shouldn't even need to install.

**Comment by alepeccioli** [comment] 2017-09-14 11:44
I did a clean install of Debian Stretch this week and added the repositories of KXStudio and the apt error no longer appears.
![captura de tela_2017-09-14_08-43-02](https://user-images.githubusercontent.com/11941436/30428128-db2794a4-9928-11e7-875a-e8025d95ef7b.png)

**Comment by alepeccioli** [comment] 2017-09-14 11:47
![captura de tela_2017-09-14_08-46-46](https://user-images.githubusercontent.com/11941436/30428260-43a247e0-9929-11e7-827d-a4630331f104.png)

**Comment by falkTX** [comment] 2017-09-14 18:10
After some investigation, I'm closing this as won't fix.
There's nothing particularly wrong with the kxstudio repo setup.
The relevant debian bug has been fixed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839259 but seems it won't make it to debian stretch.
This comment on the bug fixes the warning for current avlinux isos:
> you can remove the "deb::Contents-deb-legacy" from /etc/apt/apt.conf.d/50apt-file.conf.

**Closed by falkTX** 2017-09-14 18:10 UTC
