### ISSUE TITLE
Package request: Beast!

### ISSUE THREAD

**Issue by ghost** [KXStudio/Repository#129] opened 2017-09-30 08:13 UTC
Hi all,
here's one I think might be a good addition to the KXStudio repos (if doable) 

[https://beast.testbit.org/](url)

brian

**Comment by stragu** [comment] 2018-09-09 06:10
This is a duplicate of https://github.com/KXStudio/Repository/issues/114

**Comment by falkTX** [comment] 2019-09-23 23:07
last time I tried to package beast, it was quite a pain.
I am giving up on it.

**Closed by falkTX** 2019-09-23 23:07 UTC
